### ISSUE TITLE
Hello author, can you help me look at this problem?

### ISSUE THREAD

**Issue by ghost** [yuh-yang/KGCL-SIGIR22#17]
Traceback (most recent call last):
  File "G:/gzh/CausalRes/KnowledgeGraph/KGCL/code/main.py", line 79, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    w=w)
  File "G:\gzh\CausalRes\KnowledgeGraph\KGCL\code\Procedure.py", line 89, in BPR_train_contrast
    for batch_i, train_data in tqdm(enumerate(dataloader), total=len(dataloader),disable=True):
  File "G:\gzh_app\envs\kehao\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
  File "G:\gzh_app\envs\kehao\lib\multiprocessing\spawn.py", line 105, in spawn_main
    return self._get_iterator()
  File "G:\gzh_app\envs\kehao\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    exitcode = _main(fd)
  File "G:\gzh_app\envs\kehao\lib\multiprocessing\spawn.py", line 115, in _main
    return _MultiProcessingDataLoaderIter(self)
  File "G:\gzh_app\envs\kehao\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    w.start()
  File "G:\gzh_app\envs\kehao\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "G:\gzh_app\envs\kehao\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "G:\gzh_app\envs\kehao\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "G:\gzh_app\envs\kehao\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "G:\gzh_app\envs\kehao\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "G:\gzh_app\envs\kehao\lib\site-packages\torch\multiprocessing\reductions.py", line 150, in reduce_tensor
    storage = tensor.storage()
  File "G:\gzh_app\envs\kehao\lib\site-packages\torch\_tensor.py", line 260, in storage
    return torch.TypedStorage(wrap_storage=self._storage(), dtype=self.dtype)
NotImplementedError: Cannot access storage of SparseTensorImpl

**Comment by yuh-yang** [comment]
Hey @ZhihaoGuo817 ,

Please check your torch version, I think it should be at least 1.8.1.

**Comment by ZhihaoGuo817** [comment]
Thank you very much for your reply. My current version is 1.13.1. I will install 1.8.1 and try again.

**Comment by ghost** [comment]
> 
Thank you very much for your reply. My current version is 1.13.1. I will install 1.8.1 and try again.

**Comment by ZhihaoGuo817** [comment]
RuntimeError: sparse tensors do not have storage

**Comment by ghost** [comment]
Dear author, when I changed it to 1.8.1, the following error occurred again. Can you think of the reason?
RuntimeError: sparse tensors do not have storage

**Comment by yuh-yang** [comment]
Hey @ZhihaoGuo817 .

Sorry I never encountered this error. 

Literally I think it is saying that you are returning SparseTensor in `__get_item__` in the dataloader, which in the codes I did not do indeed. Could you check more about the environment requirements, or did you modify the codes for extra features?

**Comment by ghost** [comment]
Hey @yuh-yang 
The error on the first run is:
The "freeze_support()" line can be omitted if the program
is not going to be frozen to produce an executable.

Then, I put the code in the main function after it,
if name = = "main ':

When I ran it again, I had the original error.

**Comment by yuh-yang** [comment]
Sry I'm not quite sure about what that "freeze_support()" issue means at first. So I googled it and learned that it is because you are running the codes in Windows.

Do you happen to have a Linux environment? Maybe give it a try to run the code in Linux and let's see if there is still SparseTensor error.

**Comment by yuh-yang** [comment]
Yes. Please just feel free to discuss. :)
